### PR TITLE
Address Issue #225

### PR DESCRIPTION
**Pull request by adgiles**
Changed Radius 1 and 2 schemas from Short Int to Long Int

### CODE REVIEW

**Comment by csmoore** [comment]
Not sure if a good time to do this, but there was also another issue to rename this schema GDB to something other than "scratch" - #229

**Comment by adgiles** [comment]
Probably better to be called Schema

**Comment by csmoore** [comment]
While I'm testing this tool - I can verify this

**Comment by csmoore** [comment]
Verified:

image

**Pull request merged**
